version: "3.8"

services:
  digital-money-house:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digital-money-house-app
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
