import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { headers } from "next/headers";

import Navbar from "@/app/components/layout/navbar";

import Footer from "@/app/components/layout/footer";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "600", "700"], // regular, semibold, bold
  style: ["normal", "italic"], // add italic style
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  //Same that usePathname in client components but for server components
  const headersList = await headers();
  const currentPath = headersList.get("x-invoke-path") || "/";

  // Show sign-in button depending on the current path
  const showSignInButton = currentPath === "/" || currentPath === "/signup";

  return (
    <html lang="es">
      <body
        className={`${openSans.variable} flex min-h-[100dvh] flex-col antialiased`}
      >
        <header>
          <Navbar showSignInButton={showSignInButton} isLoggedIn={!!session} />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
