import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";
import { SidebarProvider } from "@/contexts/sidebar-context";
import { SessionProvider } from "next-auth/react";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "600", "700"], // regular, semibold, bold
  style: ["normal", "italic"], // add italic style
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${openSans.variable} flex min-h-[100dvh] flex-col antialiased`}
      >
        <SessionProvider>
          <SidebarProvider>
            <header>
              <Navbar />
            </header>
            {children}
            <Footer />
          </SidebarProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
